version: '2'
services:
    chatserver-app:
        image: chatserver
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://chatserver-postgresql:5432/chatserver
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    chatserver-postgresql:
        extends:
            file: postgresql.yml
            service: chatserver-postgresql
